; PlatformIO configs 


[env:nano]
platform = atmelavr
board = nano
framework = arduino
monitor_speed = 9600
upload_speed = 57600

; Libraries used in the project
lib_deps = 
    adafruit/Adafruit SSD1306@^2.5.13
    adafruit/Adafruit GFX Library@^1.11.11
    nRF24/RF24@^1.4.11

; Build options
build_flags = 
    -D CORE_DEBUG_LEVEL=0
