; PlatformIO configs 

[env:nano]
platform = atmelavr
board = nano
framework = arduino
monitor_speed = 9600
upload_speed = 57600

lib_deps = 
    frankdebrabander/LiquidCrystal_I2C@^1.1.7
    nRF24/RF24@^1.4.11
